apiVersion: v1
kind: Secret
metadata:
  name: backend-env
type: Opaque
data:
  PORT: "ODAwMA=="
  FRONTEND_URL: "aHR0cDovL2xvY2FsaG9zdDozMDAw"
  MONGODB_URI: "bW9uZ29kYitzcnY6Ly9uYW1hbnJhajQ4ODpuYW1hbnJhajI0QG5leHRhcHAtY2x1c3Rlci5paWtuOS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TmV4dEFwcC1DbHVzdGVy"
  MONGODB_DATABASE: "UHJvcGVydHlJbmZv"
  AWS_ACCESS_KEY_ID: "QUtJQVozTUdOT0RIVEJKWDY1Q0c="
  AWS_SECRET_ACCESS_KEY: "YUw1ak5YQUtBOHZpbVJvUzZTTUZGenpyNzhrd21EUldEaTlUekxzSQ=="
  AWS_REGION: "YXAtc291dGgtMQ=="
  AWS_S3_BUCKET: "cHJvcGVydHlsaXN0aW5nLWJ1Y2tldA=="
  OPENAI_API_KEY: "c2stcHJvai1yYm56eHo0eUxOWXdrQk1nX1BpM3d3SW95bkRTdVl3bVZneVZwNGpMOHd3N3lYM1dSOVhVV3Mxc19ERnFucjVDdGtCLVNoVUh4ZlQzQmxia0ZKNUR1RGhER0xqSVRvZ2NTUzQ3MVFYQjg1NGh1RWs1LVRDLVdKbXotOTR2a000Z3ZhNmtCLXNNSXhwS0Z6R3oxdzI3V3BORjZZNEE="
  MAX_FILE_SIZE: "MTA0ODU3NjA="
  ALLOWED_FILE_TYPES: "aW1hZ2UvanBlZyxpbWFnZS9qcGcsaW1hZ2UvcG5nLGltYWdlL3dlYnA="
