apiVersion: v1
kind: Service
metadata:
  name: property-brochure-backend-service
spec:
  selector:
    app: property-brochure-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
